### ISSUE TITLE
Objections about looking storcli(64) in /opt/MegaRAID/storcli?

### ISSUE THREAD

**Issue by matsimon** [thomas-krenn/check_lsi_raid#14]
Hi

When StorCLI gets installed via the current Broadcom's rpm or deb packages they are always located in /opt/MegaRAID/storcli. That location hasn't changed over the years where LSI has become Avago then Broadcom.

Any objections about extending the current logic around [Line 1255](https://github.com/thomas-krenn/check_lsi_raid/blob/master/check_lsi_raid#L1255-L1260) to also check in /opt/MegaRAID/storcli?

What's the motivation: Make check_lsi_raid might "just work" once the storcli is installed using the Broadcom-provided Linux packages for rpm- and deb-based distributions without the need to provide a -p/--path when using the Broadcom packages.

**Comment by gschoenberger** [comment]
Good idea!
Can you test commit 8bc89496b3df7716729528528a68b807897765f9 ?

**Comment by matsimon** [comment]
Hey, cool!

Confirmed working with StorCLI 1.23.02 on Debian jessie against some IBM ServeRAID-branded adapter.

Since I'm on the go (not pull request, sorry), here is a small diff that might update the help message to go with the new "default".

```
--- check_lsi_raid.orig	2017-10-18 13:38:18.903880040 +0200
+++ check_lsi_raid	2017-10-18 13:42:15.738697696 +0200
@@ -126,7 +126,7 @@
     threshold is $IGNERR_B.\n";
 	print "  [ -p <path> | --path <path>]
     Specifies the path to StorCLI, per default uses the tool 'which' to get
-    the StorCLI path.\n";
+    the StorCLI path, also checks in /opt/MegaRAID/storcli.\n";
 	print "  [ -b <0/1> | --BBU <0/1> ]
     Check if a BBU or a CacheVault module is present. One must be present unless
     '-b 0' is defined. This ensures that for a given controller a BBU/CV must be
@@ -161,8 +161,8 @@
 if you have questions regarding use of this software, to submit patches, or
 suggest improvements.
 Example usage:
-* check_lsi_raid -p /opt/MegaRAID/storcli/storcli64
-* check_lsi_raid -p /opt/MegaRAID/storcli/storcli64 -C 1\n";
+* check_lsi_raid
+* check_lsi_raid -p /usr/local/sbin/storcli64 -C 1\n";
 	exit(STATE_UNKNOWN);
 }
```

**Comment by gschoenberger** [comment]
I have added your help text with commit ef35fc4a23cf69bf8cf7afec367a2d1deec5a9bc !

**Comment by matsimon** [comment]
Thank you Georg, that's perfect for me.
