### ISSUE TITLE
How to monitor ESXi host

### ISSUE THREAD

**Issue by kasimovv** [thomas-krenn/check_lsi_raid#16]
Hello. Could you help me, please.
Is it possible to monitor ESXi host with this plugin with Nagios ?
On esxi server i installed storcli and it works good if i execute commands manually.

Best regars
Vil Kasimov

**Comment by tk-wfischer** [comment]
Hi Vil,

I'm not aware of a way to e.g. setup NRPE on an ESXi host. Maybe it's possible to implement such a check using check_by_ssh - but I have not tried such a setup yet.

Another alternative would be to use the CIM-providder and this plugin: https://www.claudiokuenzler.com/nagios-plugins/check_esxi_hardware.php

Best regards,
Werner

**Comment by kasimovv** [comment]
Hello, Werner. Thank you for the reply. Yes, we are using this plugin (check_esxi_hardware) and CIM-provider. But sometimes our ESXi hosts goes to PSOD because of this CIM. Without CIM hosts works fine. 
Now we want to delete all cim-providers from our hosts, and use some nagios -plugin or some script to check raid status. Unfortunately there is now NRPE vib packets for ESXi. Maybe there is a way to check raid using snmp check.
