### ISSUE TITLE
CTR_Memory_correctable_errors 

### ISSUE THREAD

**Issue by omm0910** [thomas-krenn/check_lsi_raid#25]
Please pardon if this is wrong forum to ask.
Curious what purpose or action can one take when a LSI RAID card exhibits small or limited increase in CTR memory correctable errors. We have a card with this situation and check_lsi_raid is in warning status about CTR_Memory_correctable_errors count of 4 ( not incrementing over time - appears static) Is there a value setting which we can set - similar to the many TEMP values which can be optimized to eliminate noise.

**Comment by omm0910** [comment]
I 've found the bit that triggers this WARNING 
section between lines 327..334
Would you consider changing from the current
        elsif ( $key eq 'Memory Correctable Errors' ) {
            if ( $foundController{$key} != 0) {
                $status = 'Warning' unless $status eq 'Critical';
                push @{ $statusLevel_a[1] }, 'CTR_Memory_correctable_errors';
                $statusLevel_a[3]->{'CTR_Memory_correctable_errors'} =
                  $foundController{$key};
            }

to establishing a variable for Memory Correctable Errors Count and inserting into this logic 
then a value could be set to eliminate sporadic values?

**Comment by gschoenberger** [comment]
Can you test commit b7a74710f25e999d81eaa2168238bab593d56ccf ?

**Comment by omm0910** [comment]
thanks! appears to work quite well - regards
