### ISSUE TITLE
Use of uninitialized value $lineVals[1] in substitution (s///) at ./check_lsi_raid line 250

### ISSUE THREAD

**Issue by PVasileff** [thomas-krenn/check_lsi_raid#32]
I have download script latest version 2.5 from git and running on my server with AVAGO MegaRAID SAS 9361-8i
and I got:

`Use of uninitialized value $lineVals[1] in substitution (s///) at ./check_lsi_raid line 250`

Please tell me, how to fix that ?

**Comment by gschoenberger** [comment]
Version 2.5 is from 2016, i have to realease a new version - will do that soon.
Meanwhile, can you try lastest master from git?

**Comment by PVasileff** [comment]
Sorry for my miscomunnication. 

I have downloaded script from:

https://raw.githubusercontent.com/thomas-krenn/check_lsi_raid/master/check_lsi_raid

(from master) 

and I wrote version 2.5, because I found it on script:

`our $VERSION = "2.5";
`

I have hide the error:

`Use of uninitialized value $lineVals[1] in substitution (s///) at ./check_lsi_raid line 250
`

when on line 248 replace:

`                        my @lineVals = split('=', $line);`

with

`                        my @lineVals = split(':', $line);`

is that correct ?

**Comment by gschoenberger** [comment]
Can you post the storcli output for "show all"?

**Comment by PVasileff** [comment]
```
CLI Version = 007.1613.0000.0000 Oct 29, 2020
Operating system = Linux 5.4.106-1-pve
Status Code = 0
Status = Success
Description = None

Number of Controllers = 1
Host Name = pve
Operating System  = Linux 5.4.106-1-pve

System Overview :
===============

------------------------------------------------------------------------------------
Ctl Model                   Ports PDs DGs DNOpt VDs VNOpt BBU sPR DS  EHS ASOs Hlth 
------------------------------------------------------------------------------------
  0 AVAGOMegaRAIDSAS9361-8i     8   7   2     0   2     0 Opt On  1&2 Y      5 Opt  
------------------------------------------------------------------------------------

Ctl=Controller Index|DGs=Drive groups|VDs=Virtual drives|Fld=Failed
PDs=Physical drives|DNOpt=Array NotOptimal|VNOpt=VD NotOptimal|Opt=Optimal
Msng=Missing|Dgd=Degraded|NdAtn=Need Attention|Unkwn=Unknown
sPR=Scheduled Patrol Read|DS=DimmerSwitch|EHS=Emergency Spare Drive
Y=Yes|N=No|ASOs=Advanced Software Options|BBU=Battery backup unit/CV
Hlth=Health|Safe=Safe-mode boot|CertProv-Certificate Provision mode
Chrg=Charging | MsngCbl=Cable Failure

ASO :
===

----------------------------------------------------
Ctl Cl SAS MD R6 WC R5 SS FP Re CR RF CO CW HA SSHA 
----------------------------------------------------
  0 X  U   X  U  U  U  U  U  X  U  X  X  U  X  X    
----------------------------------------------------

Ctl=Controller Index|Cl=Cluster|MD=Max Disks|WC=Wide Cache|SS=Safe Store|FP=Fast Path
Re=Recovery|CR=CacheCade(Read)|RF=Reduced Feature Set|CO=Cache Offload
CW=CacheCade(Read/Write)|X=Not Available/Not Installed|U=Unlimited|T=Trial
|HA=High Availability |SSHA=Single server High Availability 




```

**Comment by gschoenberger** [comment]
This is definitively a bug produced while merging for  #31
Can you test commit db1093cd227cd93cfd00246662b18375cd2f4bf1
I did a quick a test which was successful!

**Comment by PVasileff** [comment]
I have dowloaded script again from:

https://raw.githubusercontent.com/thomas-krenn/check_lsi_raid/master/check_lsi_raid

Now everything work as well.

Thank you very much!
