### ISSUE TITLE
Can't use an undefined value as an ARRAY reference at ./check_lsi_raid

### ISSUE THREAD

**Issue by dmitrykrivitsky** [thomas-krenn/check_lsi_raid#36]
I am getting the following:

./check_lsi_raid -p /opt/MegaRAID/storcli/storcli64 -C 0 --nocleanlogs
Can't use an undefined value as an ARRAY reference at ./check_lsi_raid line 408.

Line 408 is:
for(my $i = 0; $i < @{$LDMAP}; $i++){

**Comment by dmitrykrivitsky** [comment]
I found what the problem was.
The header line may have more than one white space.
Line
   if($line =~ /^DG\/VD TYPE.*/){
needs to be replaced with
   if($line =~ /^DG\/VD[[:blank:]]+TYPE.*/){

**Comment by gschoenberger** [comment]
Can you try laster commit a983b1fb10a6cdf1390413daabb93ebd0823d12a ?

**Comment by dmitrykrivitsky** [comment]
> Can you try lastet commit [a983b1f](https://github.com/thomas-krenn/check_lsi_raid/commit/a983b1fb10a6cdf1390413daabb93ebd0823d12a) ?

Yes, it is working now. Thanks.

**Comment by dmitrykrivitsky** [comment]
> I found what the problem was. The header line may have more than one white space. Line if($line =~ /^DG/VD TYPE._/){ needs to be replaced with if($line =~ /^DG/VD[[:blank:]]+TYPE._/){

Just for the record: special characters got corrupted when I was pasting this code into my comment... I guess the comment section doesn't like special characters.
