### ISSUE TITLE
Plugin does not show Intel SSDs in performance data

### ISSUE THREAD

**Issue by ronator** [thomas-krenn/check_lsi_raid#4]
Hi, I am testing this plugin with a "LSI MegaRAID SAS 9260CV-8i" and with a "LSI MegaRAID SAS 9260-8i" on an ubuntu 12.04 with kernel 3.8 and using plugin defaults (controller 0). Both servers have 9 physical disks with 8 disks online for RAID.
I implemented this plugin on the first server with nrpe and icinga2 and it work great; thank you!

Then I used the same setup for another server. Surprisingly, the check on this server output different performance data based on the disks it can find. For the second server, I can only get performance data for s0 to s3 but NOT for s4 to s8 - they are not visible.
I went to the server console and found out, that these disks are SSDs with SATA interface.

So it seems to work fine with these disks, they are all shown in web ui and console
- Med=HDD
- Model=TOSHIBA MK2002TSKB

But for some reasons, the SSDs are not shown, neither in the monitoring web ui nor on the command line. The only difference I can see, is HDD here and SSD there (SAS here and SATA there).
- Med=SSD
- Model=INTEL SSDSC2CW180A3

I am not sure what is causing this:
- Actually, I do have consistency errors on both virtual disks (NOT degraded) - could that be the reason?
- I have an old driver on the server and an old firmware on the controller
- storcli and megacli have no trouble showing me the SSD disks in question

Maybe it is not  a problem of the plugin and maybe this is NOT an issue. But since 'storcli' works flawlessly, I am wondering why some SSD disks are not shown by the plugin performance data but by storcli/megacli? Maybe someone could enlighten me.

Thank you for your time.

**Comment by gschoenberger** [comment]
Can you post the output of the following storcli commands?
 - /usr/bin/sudo /opt/MegaRAID/storcli/storcli64 /c0 /cv show status
- /usr/bin/sudo /opt/MegaRAID/storcli/storcli64 adpallinfo a0
- /usr/bin/sudo /opt/MegaRAID/storcli/storcli64 /c0/vall show all
- /usr/bin/sudo /opt/MegaRAID/storcli/storcli64 /c0/vall show init
- /usr/bin/sudo /opt/MegaRAID/storcli/storcli64 /c0/eall/sall show all
- /usr/bin/sudo /opt/MegaRAID/storcli/storcli64 /c0/eall/sall show initialization
- /usr/bin/sudo /opt/MegaRAID/storcli/storcli64 /c0/eall/sall show rebuild

**Comment by ronator** [comment]
For sure. I executed these commands in the exact same order as requested and appended it all to the file attached.

[storcli.txt](https://github.com/thomas-krenn/check_lsi_raid/files/371482/storcli.txt)

Thank you for your help.

**Comment by ronator** [comment]
I am sorry, I posted wrong output! Wait a sec ...

**Comment by ronator** [comment]
This is the correct output with the disks in question ...
[storcli.txt](https://github.com/thomas-krenn/check_lsi_raid/files/371491/storcli.txt)

Thank you for your support.

**Comment by ronator** [comment]
I went on with another (old) server with 8 physical disks and some SSDs. This RAID seems good, but here are also some disks missing in the output.

OK (CTR, LD, PD, CV)|CV_Temperature=21;70;85 c0/e252/s0_Drive_Temperature=32;40;45 c0/e252/s1_Drive_Temperature=27;40;45 c0/e252/s2_Drive_Temperature=31;40;45 c0/e252/s3_Drive_Temperature=30;40;45

Again, the SSDs are not shown by plugin but but storcli:
-----------------------------------------------------------------------------
EID:Slt DID State DG       Size Intf Med SED PI SeSz Model                Sp 
-----------------------------------------------------------------------------
252:0     9 Onln   0   1.818 TB SATA HDD N   N  512B TOSHIBA MK2002TSKB   U  
252:1    11 Onln   0   1.818 TB SATA HDD N   N  512B WDC WD20EARX-00PASB0 U  
252:2    10 Onln   0   1.818 TB SATA HDD N   N  512B TOSHIBA MK2002TSKB   U  
252:3     8 Onln   0   1.818 TB SATA HDD N   N  512B TOSHIBA MK2002TSKB   U  
252:4    13 Onln   1 167.156 GB SATA SSD N   N  512B INTEL SSDSC2CW180A3  U  
252:5    12 Onln   1 167.156 GB SATA SSD N   N  512B INTEL SSDSC2CW180A3  U  
252:6    14 Onln   1 167.156 GB SATA SSD N   N  512B INTEL SSDSC2CW180A3  U  
252:7    15 Onln   1 167.156 GB SATA SSD N   N  512B INTEL SSDSC2CW180A3  U  
-----------------------------------------------------------------------------

**Comment by ronator** [comment]
I may have to add that I converted the storcli.rpm with 'alien' to a deb file, so maybe this only happens with Ubuntu?

**Comment by gschoenberger** [comment]
OK, I thin I can remember the issue now. There's no perf data for SSD as storcli is not reporting any for SSDs. E.g. from your output:
```
----------------------------------------------------------------------------
EID:Slt DID State DG       Size Intf Med SED PI SeSz Model               Sp 
----------------------------------------------------------------------------
252:4    14 Onln   1 167.156 GB SATA SSD N   N  512B INTEL SSDSC2CW180A3 U  
----------------------------------------------------------------------------
[...]
Drive /c0/e252/s4 - Detailed Information :
========================================
Drive /c0/e252/s4 State :
=======================
Shield Counter = 0
Media Error Count = 0
Other Error Count = 0
Drive Temperature = N/A
Predictive Failure Count = 0
S.M.A.R.T alert flagged by drive = No
```

**Comment by ronator** [comment]
Oh, I see, thanks for pointing that out. Then I guess you can close this issue as it is a problem of storcli. By now, I'm still unsure how I will handle this situation - maybe I drop them storcli developers a line if this feature could be possible . I understand that if storcli is "suddenly" report the missing data, then the plugin should also show it, right? So maybe I might report back to you on storcli.

**Comment by gschoenberger** [comment]
If storcli would report it, the plugins adds it to the perf data:
```
if($temp ne 'N/A' && $temp ne '0C (32.00 F)'){
[...]
```
Meanwhile you could use my check_smart_attributes Plugin:
- https://github.com/thomas-krenn/check_smart_attributes/blob/master/check_smart_attributes.README
There you should get the temperature and SSD lifetime from the SMART attributes, depending on the SSDs you are using.
You can open an issue there if your SSDs are not in the smartdb JSON file!

- Georg

**Comment by ronator** [comment]
Thank you very much for listing this alternative, I will check it out.
Besides that, I reached someone at "Avago" (they bought LSI) who have the "copyright" on storcli. They seem very nice, asking me for more info on this issue. So thanks again for your help, I may use your suggested Plugin, depending on the outcome with Avago and storcli.

Best
Ron
