### ISSUE TITLE
Problems with GasGauge / CacheVault / BBU on 9260-8i

### ISSUE THREAD

**Issue by ronator** [thomas-krenn/check_lsi_raid#6]
Hi there,

I have an (old) LSI MegaRAID SAS 9260-8i. Yesterday, I replaced the battery and build a new RAID and installed a fresh Linux. I use 'storcli' (v1.20) to check the controller state. Now, after a consistency check, this nice plugin is still reporting problems with the BBU state / GasGauge. I tested it with the current git version:

Critical (BBU Crit) [BBU_​GasGauge_​discharged = Critical (A)​]​[BBU_​GasGauge_​over_​charged = Critical (A)​]​[BBU_​GasGauge_​over_​temperature = Warning (A)​]

Thats what I also see in very very verbose mode:
[...]
BBU information:
        - BBU_GasGauge_discharged=A
        - BBU_GasGauge_over_charged=A
        - BBU_GasGauge_over_temperature=A
        - BBU_Status=Critical
        - BBU_Temperature=36

When I ask storcli to get me that info, it basically tells me, there are no sensors for this:

**$ storcli64  /c0/bbu show**

Controller = 0
Status = Success
Description = None

BBU_Info :
Model  State   RetentionTime Temp Mode MfgDate    Next Learn 
iBBU08 Optimal 48 hours +    36C  3    2016/05/30 None       

If I dig deeper, I get:

**$ storcli /c0 /bbu show status**

Controller = 0
Status = Success
Description = None

BBU_Info :
Property      Value
Type          iBBU08
Voltage       4088 mV
Current       0 mA
Temperature   36 C
**Battery State Optimal**
Design Mode   3: 24+ Hrs retention with a transparent learn cycle 
                 and balanced service life.                       

BBU_Firmware_Status :
Property                                   Value 
Charging Status                            None  
Voltage                                    OK  
Temperature                                OK  
Learn Cycle Requested                      No  
Learn Cycle Active                         No  
Learn Cycle Status                         OK  
Learn Cycle Timeout                        No  
I2C Errors Detected                        No  
Battery Pack Missing                       No  
Replacement required                       No  
Remaining Capacity Low                     No  
Periodic Learn Required                    No  
Transparent Learn                          No  
No space to cache offload                  No  
Pack is about to fail & should be replaced No  
Cache Offload premium feature required     No  
Module microcode update required           No    

GasGaugeStatus :
Property                   Value  
GasGauge StatusCode        0x280  
**Fully Discharged           N/A**
Fully Charged              N/A  
Discharging                N/A
Initialized                N/A  
Remaining Time Alarm       N/A  
Terminate Discharge Alarm  N/A  
Over Temperature           N/A  
Charging Terminated        N/A  
**Over Charged               N/A**
Relative State of Charge   100%  
Charger System State       1  
Charger System Ctrl        0  
Charging current           0 mA  
Absolute state of charge   89%  
Max Error                  0%  
Battery backup charge time 48 hours + 

The problem is, IMHO "GasGauge" comes with "Cache Vault", which my model simply does NOT support, so there will never be such info. Furthermore, I am wondering if the plugin might cut down the result since 'storcli' clearly says "N/A" whereas the plugin reports just "A".

I am using the following software/firmware:
Versions
Product Name    : LSI MegaRAID SAS 9260-8i
Serial No       : SV92800992
FW Package Build: 12.15.0-0239

Image Versions in Flash:
FW Version         : 2.130.403-4660
BIOS Version       : 3.30.02.2_4.16.08.00_0x06060A05
Preboot CLI Version: 04.04-020:#%00009
WebBIOS Version    : 6.0-54-e_50-Rel
NVDATA Version     : 2.09.03-0058
Boot Block Version : 2.02.00.00-0000
BOOT Version       : 09.250.01.219
###### 

Is there a way to get rid of that message? I could not find any options to disable this "faulty detection". I did not try to upgrade drivers or firmware because I do not see the error within the storage controller. And since the controller does not support "Cache Vault", I tend to think it will not go away with firmware upgrade, but maybe I am wrong.

Do you need more info/output? Could this be a bug? Can it be fixed? Shouldn't this happen with all devices without CacheVault? Do you need help with this - e.g. should I try and create a commit request (I looked into the code a little)?

**Please let me know if I should provide any more info on this issue - I would be glad to help to "fix" this.**

**Comment by ronator** [comment]
Driver Name = megaraid_sas
Driver Version = 06.810.09.00-rc1
(Yes, "rc1" but I guess upgrade won't fix the problem/output)

**Comment by tk-wfischer** [comment]
I'll speak to my colleague Georg and will look at your issue. We will keep you updated.

**Comment by gschoenberger** [comment]
THX for the issue!
Could you try the latest version from git?
I am checking for the N/A string now, commit 4a772b708b37efe8d2c6a2d76a8f6dc3f5feda9c

- Georg

**Comment by ronator** [comment]
Yes, I had a look into the code, looks good, and I tested the new version. Without performance data, I get now:
**OK (CTR, LD, PD, BBU)**
So obviously, my issue with controllers without GasGauge/CacheVault is gone now. Awesome, so **thank you**, too, guys; quick and straightforward commit; very much appreciated.
